### ISSUE TITLE
error during install strechr/testify, undefined: errors.Is

### ISSUE THREAD

**Issue by XanderDwyl** [stretchr/testify#991]
go get github.com/stretchr/testify/assert

src/github.com/stretchr/testify/assert/assertions.go:1703:5: undefined: errors.Is
src/github.com/stretchr/testify/assert/assertions.go:1726:6: undefined: errors.Is
src/github.com/stretchr/testify/assert/assertions.go:1749:5: undefined: errors.As
src/github.com/stretchr/testify/assert/assertions.go:1766:7: undefined: errors.Unwrap
src/github.com/stretchr/testify/assert/assertions.go:1770:7: undefined: errors.Unwrap

**Comment by boyan-soubachov** [comment]
Master will only work with Go 1.13+
